name: Build, Push Image and Deploy
on:
  workflow_dispatch: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from package.json
        id: version
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
          
      - name: Set image tag
        id: image-tag
        run: |
          if [[ "${{ github.ref_name }}" == "master" || "${{ github.ref_name }}" == "production" ]]; then
            echo "tag=${{ steps.version.outputs.VERSION }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.image-tag.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Update GitOps repo with new image tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
  
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/huuphuc-nguyen/gitops-infras.git
          cd gitops-infras

          # Update values.yaml image tag
          yq eval ".image.tag = \"${{ steps.image-tag.outputs.tag }}\"" -i projects/personal-project/apps/tictactoe/values.yaml

          # Also update Chart.yaml appVersion and/or version
          yq eval ".appVersion = \"${{ steps.version.outputs.VERSION }}\"" -i projects/personal-project/apps/tictactoe/Chart.yaml
          
          git add .
          git commit -m "Cicd:Update image tag of ImageReveal to ${{ steps.image-tag.outputs.tag }}"
          git push
